version: '3.0.1'
services:
  back:
    build: ./back
    working_dir: /back
    volumes:
      - ./back:/back
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
  front:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - ./front/.env
    restart: always
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass examplePassword
    volumes:
      - cache:/data
  database:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6543:5432
volumes:
  cache:
  postgres_data:
